# Generated by Django 2.0.13 on 2020-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
