# Generated by Django 2.0.13 on 2020-09-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_project_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
    ]
