# Generated by Django 2.0.13 on 2020-09-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_project_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(default='Work', on_delete=django.db.models.deletion.CASCADE, to='resume.Section'),
            preserve_default=False,
        ),
    ]
